[build]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "dist/netlify/functions"

[dev]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
