[build]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  directory = "dist/netlify/functions"

[dev]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "public"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/create-playlist"
  to = "/.netlify/functions/create-playlist"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
